spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/how2java?characterEncoding=UTF-8
      username: root
      password: sys
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    http:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      pool:
        min-idle: 0
        max-wait: -1
        max-idle: 8
        max-active: 8
      timeout: 0
    thymeleaf:
      cache: false
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
#spring boot 1.5.9
server:
  port: 8888
  context-path: /test
#spring boot 2.0.5
#server:
#    port: 8888
#    servlet:
#      context-path: /test

#mybatis:
#  mapper-locations: classpath:com/example/panda/mapper/*.xml
#  type-aliases-package: com.example.panda.pojo