spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/how2java?characterEncoding=UTF-8
      username: root
      password: sys
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
    http:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
#spring boot 1.5.9
server:
  port: 8888
  context-path: /test
#spring boot 2.0.5
#server:
#    port: 8888
#    servlet:
#      context-path: /test
#mybatis:
#  mapper-locations: classpath:com/example/panda/mapper/*.xml
#  type-aliases-package: com.example.panda.pojo